site_name: ""
site_url: https://docs.activeagents.ai
repo_name: activeagents/activeagent
repo_url: https://github.com/activeagents/activeagent
# extra:
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: 日本語
#       link: /ja/
#       lang: ja
theme:
  features:
    - content.code.annotate
    - content.code.copy
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Space Grotesk
    code: Roboto Mono
  palette:    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences